remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-feed

title: Antoine Mandin | Software engineer
author: Antoine Mandin
email: antoine.mandin.am@gmail.com
description: >- 
  Portfolio and Resume of Antoine Mandin. French Software engineer.
baseurl: ""
url: ""
github_username: Doreapp
