remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-feed
  - jekyll-datapage-generator

title: Antoine Mandin | Software engineer
author: Antoine Mandin
email: antoine.mandin.am@gmail.com
description: >- 
  Portfolio and Resume of Antoine Mandin. French Software engineer.
baseurl: ""
url: ""
github_username: Doreapp

# Page generation configuration
# See https://github.com/avillafiorita/jekyll-datapage_gen
# page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: schools
    template: school
    name: short-name
    dir: schools
  - data: me.me
    template: index
    name: page-name
    dir: '.'
  - data: me.about
    template: about
    name: page-name
    dir: '.'
