title: Antoine Mandin | Ingénieur Logiciel
description: >-
  Portfolio d'Antoine Mandin. Ingénieur Logiciel.
baseurl: "/fr"

navbar-links:
  - ["In english", ".."]
  - ["A propos", "about"]
  - [Contact, "contact"]
